environment:
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  matrix:
    - TARGET_ARCH: x86
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda
  
    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
  
    - TARGET_ARCH: x86
      CONDA_PY: 35
      CONDA_INSTALL_LOCN: C:\\Miniconda35
  
    - TARGET_ARCH: x64
      CONDA_PY: 35
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64
  
    - TARGET_ARCH: x86
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda35
  
    - TARGET_ARCH: x64
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

platform:
  - x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  #- ps: if ("nv:APPVEYOR_PULL_REQUEST_NUMBER -and "nv:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
  #    https://ci.appveyor.com/api/projects/"nv:APPVEYOR_ACCOUNT_NAME/"nv:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
  #    Where-Object pullRequestId -eq "nv:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
  #      throw "There are newer queued builds for this pull request, failing early." }

  # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
  - cmd: rmdir C:\cygwin /s /q

  # Add path, activate `conda` and update conda.
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda

# Skip .NET project specific build phase.
build: off

build_script:
  - cmd: .\bld.bat

test_script:
  - cmd: nosetests
